### ISSUE TITLE
Could not convert `str` to `float`

### ISSUE THREAD

**Issue by sravan953** [imr-framework/virtual-scanner#13]
Steps to reproduce:
1. Register subject
2. Choose GRE sequence under acquire tab
3. Run

**Comment by sairamgeethanath** [comment]
@Mmj94 Have you checked the parameter ranges for other variables as well, since the new implementation?
My understanding was that this affected only the slice thickness. Please clarify

**Comment by Mmj94** [comment]
@sairamgeethanath it was not a problem only of the ranges. Range was in meters instead of mm and that was interfering too.
Apart from that, the main problem was that I accidentally deleted the word "thickness" from one html tag. It should be id="thickness" but instead it was id="", hence the error.
Both things should be fixed now. The rest of the parameter ranges should not be affected and I believe are the correct ones, provided by @tonggehua.
