### ISSUE TITLE
Register-Units of Measurement

### ISSUE THREAD

**Issue by ellieaniosis** [imr-framework/virtual-scanner#7]
![measurement issue](https://user-images.githubusercontent.com/51136062/58890402-8d0c2a80-86b8-11e9-9d5f-31584e7480ca.JPG)
It doesn't allow the user to choose the units of measurement that they understand after choosing a subject.

**Comment by sairamgeethanath** [comment]
Also, the metric needs to be kg and m, not cm.

**Comment by tonggehua** [comment]
The centimeter seems to be a more typical unit for height in metric systems to me; for the US it would be the feet-inch combination.

**Comment by Mmj94** [comment]
I don't see this as a bug. 
1. I agree with @tonggehua, cm is the most used unit for height in my opinion. If we use meters we will have to introduce a . or , which can lead to other bugs.
2. I implemented the option to choose between metric and imperial systems. However, since 1. only numerical phantom can be chosen at the moment, 2. the user is unable to modify any of its parameters and 3. the back-end code uses SI units only I disabled the imperial option in this case.

I can allow it if we agree on this, though.

**Comment by Mmj94** [comment]
This is not a bug anymore.
We have agreed that once the phantom is selected units will be kg for weight and cm for height.
Instead we have turned it into an enhancement point. We will allow the user to choose the combination of system and/or units he/she prefers when registering a human subject.
